version: '2.3'

services:
  web:
    build: .
    volumes:
      - ./.env:/work/app/.env:ro

  db:
    image: postgres:11
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - prod

volumes:
  db:
    external:
      name: ${DB_VOLUME}

networks:
  prod:
    external: true
