version: '2.3'

services:
  web:
    build: .
    volumes:
      - ./.env:/work/app/.env:ro
    networks:
      - prod
    ports:
      - ${PORT}:8000
    restart: always

  db:
    image: postgres:11
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - prod
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always

volumes:
  db:
    external:
      name: ${DB_VOLUME}

networks:
  prod:
    external: true
