# Generated by Django 2.1.4 on 2019-03-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='athlete_headshots/')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField(verbose_name='event date')),
                ('athlete', models.ManyToManyField(blank=True, related_name='event', to='triathlon.Athlete')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_place', models.CharField(blank=True, max_length=10)),
                ('gender_place', models.CharField(blank=True, max_length=10)),
                ('group_place', models.CharField(blank=True, max_length=10)),
                ('swimming_time', models.DurationField(blank=True, null=True)),
                ('t1', models.DurationField(blank=True, null=True)),
                ('biking_time', models.DurationField(blank=True, null=True)),
                ('t2', models.DurationField(blank=True, null=True)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Athlete')),
                ('distance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Distance')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Event')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Group')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='triathlon.Country'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.Country'),
        ),
    ]
