# Generated by Django 2.1.4 on 2019-09-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='athlete_headshots/')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField(verbose_name='event date')),
                ('swim', models.CharField(choices=[('O', 'Open water'), ('P', 'In pool')], default='O', max_length=1)),
                ('athlete', models.ManyToManyField(blank=True, related_name='event', to='triathlon.Athlete')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_place', models.IntegerField(blank=True, null=True)),
                ('gender_place', models.IntegerField(blank=True, null=True)),
                ('group_place', models.IntegerField(blank=True, null=True)),
                ('total_swim_place', models.IntegerField(blank=True, null=True)),
                ('gender_swim_place', models.IntegerField(blank=True, null=True)),
                ('group_swim_place', models.IntegerField(blank=True, null=True)),
                ('total_bike_place', models.IntegerField(blank=True, null=True)),
                ('total_place_after_bike', models.IntegerField(blank=True, null=True)),
                ('gender_bike_place', models.IntegerField(blank=True, null=True)),
                ('gender_place_after_bike', models.IntegerField(blank=True, null=True)),
                ('group_bike_place', models.IntegerField(blank=True, null=True)),
                ('group_place_after_bike', models.IntegerField(blank=True, null=True)),
                ('total_run_place', models.IntegerField(blank=True, null=True)),
                ('gender_run_place', models.IntegerField(blank=True, null=True)),
                ('group_run_place', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('bike_model', models.CharField(blank=True, max_length=100, null=True)),
                ('run_shoes_model', models.CharField(blank=True, max_length=100, null=True)),
                ('swimming_time', models.DurationField(blank=True, null=True)),
                ('t1', models.DurationField(blank=True, null=True)),
                ('biking_time', models.DurationField(blank=True, null=True)),
                ('t2', models.DurationField(blank=True, null=True)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Athlete')),
                ('bike_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.BikeType')),
                ('distance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Distance')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Event')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.Team'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='triathlon.Country'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bike_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike_coach', to='triathlon.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='run_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_coach', to='triathlon.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='swim_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swim_coach', to='triathlon.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete', to='triathlon.Team'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='triathlon_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triathlon_coach', to='triathlon.Coach'),
        ),
    ]
