# Generated by Django 2.1.5 on 2019-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0002_auto_20190130_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateTimeField(verbose_name='birth date'),
        ),
    ]
