# Generated by Django 2.1.5 on 2019-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0003_auto_20190130_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(verbose_name='birth date'),
        ),
    ]
