# Generated by Django 2.1.5 on 2019-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='athlete',
            field=models.ManyToManyField(to='triathlon.Athlete'),
        ),
    ]
