# Generated by Django 2.1.5 on 2019-01-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0008_event_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_place', models.CharField(max_length=10)),
                ('swim_time', models.TimeField(verbose_name='swim time')),
                ('transition1', models.TimeField(verbose_name='transition1 time')),
                ('bike_time', models.TimeField(verbose_name='bike time')),
                ('transition2', models.TimeField(verbose_name='transition2 time')),
                ('run_time', models.TimeField(verbose_name='run time')),
                ('total_time', models.TimeField(verbose_name='total time')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
