# Generated by Django 2.1.5 on 2019-01-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0009_auto_20190130_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Athlete'),
        ),
        migrations.AddField(
            model_name='result',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Event'),
        ),
    ]
