# Generated by Django 2.1.5 on 2019-01-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0014_result_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
    ]
