# Generated by Django 2.1.5 on 2019-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0015_remove_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='athlete',
            field=models.ManyToManyField(related_name='Events', to='triathlon.Athlete'),
        ),
    ]
