# Generated by Django 2.1.5 on 2019-01-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0016_auto_20190131_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='athlete',
            field=models.ManyToManyField(related_name='events', to='triathlon.Athlete'),
        ),
    ]
