# Generated by Django 2.1.5 on 2019-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0017_auto_20190131_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='athlete',
            field=models.ManyToManyField(blank=True, related_name='events', to='triathlon.Athlete'),
        ),
    ]
