# Generated by Django 2.1.5 on 2019-01-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0018_auto_20190131_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.Country'),
        ),
    ]
