# Generated by Django 2.1.5 on 2019-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0019_auto_20190131_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='athlete_headshots/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='athlete',
            field=models.ManyToManyField(blank=True, related_name='event', to='triathlon.Athlete'),
        ),
    ]
