# Generated by Django 2.1.5 on 2019-02-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0020_auto_20190131_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.Country'),
        ),
    ]
