# Generated by Django 2.1.5 on 2019-02-01 14:01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0021_auto_20190201_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='triathlon.City'),
        ),
        migrations.AlterField(
            model_name='result',
            name='bike_time',
            field=models.TimeField(blank=True, verbose_name='bike time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='run_time',
            field=models.TimeField(blank=True, verbose_name='run time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='swim_time',
            field=models.TimeField(blank=True, verbose_name='swim time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_place',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_time',
            field=models.TimeField(blank=True, verbose_name='total time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='transition1',
            field=models.TimeField(blank=True, verbose_name='transition1 time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='transition2',
            field=models.TimeField(blank=True, verbose_name='transition2 time'),
        ),
    ]
