# Generated by Django 2.1.5 on 2019-02-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0023_auto_20190201_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
