# Generated by Django 2.1.5 on 2019-02-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0029_remove_result_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='bike_time',
            new_name='biking_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='run_time',
            new_name='running_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='swim_time',
            new_name='swimming_time',
        ),
    ]
