# Generated by Django 2.1.5 on 2019-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0030_auto_20190202_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='running_time',
            field=models.DurationField(blank=True, verbose_name='run time'),
        ),
    ]
