# Generated by Django 2.1.5 on 2019-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0038_auto_20190204_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='b_t',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='r_t',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='s_t',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='tr1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='tr2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
