# Generated by Django 2.1.5 on 2019-02-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0039_auto_20190204_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='biking_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='running_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='swimming_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='transition1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='transition2',
        ),
    ]
