# Generated by Django 2.1.5 on 2019-02-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0040_auto_20190204_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='s_t',
            new_name='swimming_time',
        ),
    ]
