# Generated by Django 2.1.5 on 2019-02-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0041_auto_20190204_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='b_t',
            new_name='biking_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='r_t',
            new_name='running_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='tr1',
            new_name='transition1',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='tr2',
            new_name='transition2',
        ),
    ]
