# Generated by Django 2.1.5 on 2019-02-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0043_auto_20190211_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date']},
        ),
    ]
