# Generated by Django 2.1.5 on 2019-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0044_auto_20190211_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
