# Generated by Django 2.1.5 on 2019-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0046_auto_20190211_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_place0', models.CharField(blank=True, max_length=10)),
                ('group_place0', models.CharField(blank=True, max_length=10)),
                ('swimming_time0', models.DurationField(blank=True, null=True)),
                ('transition10', models.DurationField(blank=True, null=True)),
                ('full_time0', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
