# Generated by Django 2.1.5 on 2019-02-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0047_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
