# Generated by Django 2.1.5 on 2019-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0049_auto_20190228_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='biking_time0',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='running_time0',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='transition20',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
