# Generated by Django 2.1.5 on 2019-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0050_auto_20190228_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='full_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='transition1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='transition2',
        ),
        migrations.AddField(
            model_name='result',
            name='t1',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t2',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='biking_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='running_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='swimming_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
