# Generated by Django 2.1.5 on 2019-02-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0051_auto_20190228_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='test',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='test',
            name='event',
        ),
        migrations.RemoveField(
            model_name='test',
            name='group',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
