# Generated by Django 2.1.5 on 2019-03-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0055_result_gender_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Distance'),
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triathlon.Group'),
        ),
    ]
