# Generated by Django 2.1.5 on 2019-03-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0056_auto_20190307_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Distance'),
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triathlon.Group'),
        ),
    ]
