# Generated by Django 2.1.5 on 2019-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0057_auto_20190307_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
