# Generated by Django 2.1.5 on 2019-05-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0060_auto_20190520_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='bike_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike_coach', to='triathlon.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='run_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_coach', to='triathlon.Coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='triathlon_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triathlon_coach', to='triathlon.Coach'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='swim_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swim_coach', to='triathlon.Coach'),
        ),
    ]
