# Generated by Django 2.1.5 on 2019-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0061_auto_20190520_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='swim',
            field=models.CharField(blank=True, choices=[('O', 'Open water'), ('P', 'In pool')], default='O', max_length=1, null=True),
        ),
    ]
