# Generated by Django 2.1.5 on 2019-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0062_event_swim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='swim',
            field=models.CharField(choices=[('O', 'Open water'), ('P', 'In pool')], default='O', max_length=1),
        ),
    ]
