# Generated by Django 2.1.5 on 2019-05-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0063_auto_20190520_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bike_type',
            new_name='BikeType',
        ),
    ]
