# Generated by Django 2.1.5 on 2019-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0065_result_bike_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='bike_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='run_shoes_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
