# Generated by Django 2.1.5 on 2019-05-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0071_auto_20190522_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
