# Generated by Django 2.1.5 on 2019-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0072_auto_20190527_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['total_place']},
        ),
    ]
