# Generated by Django 2.1.5 on 2019-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0073_auto_20190527_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='total_place',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
