# Generated by Django 2.1.5 on 2019-05-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0076_auto_20190527_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='country',
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triathlon.City'),
        ),
    ]
