# Generated by Django 2.1.5 on 2019-05-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triathlon', '0077_auto_20190527_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
    ]
